# Generated by Django 4.1.7 on 2023-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='initials',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
